language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
  - mvn clean package
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn versioneye:update
  - mvn clean cobertura:cobertura coveralls:report

env:
  global:
     # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
     #   via the "travis encrypt" command using the project repo's public key
     - secure: "S/opld1QT+DNlT0+v9Qub1L/SExVLCNgKz8I0GV6TrouhWcXCrxEj9ALAgKgTyJTM1DYEZwbbrR1kaAYCtyvtOIp/iSNTfXFw2iAClDfYoZ5YuepTkOdWNwmKasI2Wyn6+Cus3tgoJaBUnlMoEz1uu1iRuW5vmqNR5/RgmQUVao8U7VGUd1JOn3lZtd8CPRPXHZSLfk73HqDTddJz4/ofvmj1/Tijx5026igcQOT6otJG/J203TNBTtzuvnyJb+QbTDXb7NeOXSYUlAbYayQLdBw/4paIaW+kdTeuafGvjvGAUKixJ3aho2+K8dsG+AC3/zMXCZkx9tWS73aRgsXYmFbhMR4ytmiv/vgQh1n4UzHFU+KxAqMjdYx9BQcmTcPsBdXd0D9ZwJwltZaZ3WfAoU819jxRYcUPJgoUl5Tr6FEojlh0xf1RADReKpo78PjcTyt304KZbvq+Vh0QSHFHYKyN34AX0kSKA/NwhrhZPkJhZZ+T/mC3uGVYzGytF2k687aA/0Q66X2r5CR21zme+PTEXN6GHcyfHjKk0oN3Cr0RnplwqHOAmDXbC8hGXIgHjZGze5RITvJzvtO4Enh8WgIoneppdKdLJXXPpUMtBZcE1xtj0wyrOvM9b+7TN602A0QzYrwYuSH5oBfUJN1zaXrzSkr1+wIEIdOiZ74lx8="

  addons:
    coverity_scan:
      project:
        name: "Iurii-Dziuban/spring-batch-sandbox"
        description: "Build submitted via Travis CI"
      notification_email: ydzyuban@gmail.com
      build_command_prepend: "mvn clean"
      build_command:   "mvn compile -DskipTests"
      branch_pattern: master
